version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=chuck111
      - MYSQL_DATABASE=XIssueTracker
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/

  xissuetrackgo:
    image: xissuetrackgo:latest
    ports:
      - '8088:8088'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=xissuetrackgo
      - MYSQL_PASSWORD=chuck111
    #entrypoint: ['sh','-c','sleep 2073600']
    entrypoint: './xissuetrackgo'
    depends_on:
      - mysql

volumes:
  mysql:

